language: node_js
node_js:
    - "6"
    - "7"
services:
    - mongodb
cache:
    directories:
        - "node_modules"

install:
    - npm install
git:
    depth: 2

before_script:
    - sleep 15

script:
    - npm test
